apiVersion: v1
kind: Endpoints
metadata:
  name: ${ELASTICSEARCH_SERVICE}
  namespace: ${NAMESPACE}
subsets:
  - addresses:
      - ip: ${ELASTICSEARCH_IP}
    ports:
      - port: 9200
        protocol: TCP
