apiVersion: v1
kind: Service
metadata:
  name: ${KIBANA_NAME}
  namespace: ${NAMESPACE}
spec:
  type: ClusterIP
  ports:
    - name: kibana-port
      port: 5601
      protocol: TCP
      targetPort: 5601
  selector:
    application: ${KIBANA_NAME}
